function handleQuestionaireSave (req: any, res: any) {
    const {
        match_likes_nature,
        most_important_in_relationship,
        max_match_distance,
        min_search_age,
        max_search_age,
        important_match_has_made_trips,
        wants_to_travel_fast,
        where_have_you_been,
        favorite_holiday_destination,
        holiday_formats,
        plans_ahead,
        likes_to_hike,
        likes_trans_atlantic,
        where_do_you_want_to_go,
        amount_of_trips_made,
        favorite_travel_time,
        wants_to_marry,
        relationship_reason,
        children,
        drinks_alcohol,
        smokes,
        likes_nature,
        music_genre,
        yearly_earns,
        birthdate,
        hometown,
        job_title,
        length,
        profile_description,
    } = req.body

    console.log(
        match_likes_nature,
        most_important_in_relationship,
        max_match_distance,
        min_search_age,
        max_search_age,
        important_match_has_made_trips,
        wants_to_travel_fast,
        where_have_you_been,
        favorite_holiday_destination,
        holiday_formats,
        plans_ahead,
        likes_to_hike,
        likes_trans_atlantic,
        where_do_you_want_to_go,
        amount_of_trips_made,
        favorite_travel_time,
        wants_to_marry,
        relationship_reason,
        children,
        drinks_alcohol,
        smokes,
        likes_nature,
        music_genre,
        yearly_earns,
        birthdate,
        hometown,
        job_title,
        length,
        profile_description
    )

    res.redirect('/matches_overview')
}

export default handleQuestionaireSave
